# Generated by Django 2.2.2 on 2019-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='candidate_first_name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='candidate_last_name',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
